---
# tasks file for pvwa_extract

- name: Create folder
  win_file:
    path: "{{ pvwa_extract_folder }}"
    state: directory

- name: Copy PVWA package from local source
  win_copy:
    src: "{{ pvwa_zip_file_path }}"
    dest: "{{ pvwa_extract_folder }}\\{{ pvwa_artifact_name }}"

- name: Get information about PVWA package
  stat:
    path: "{{ pvwa_extract_folder }}\\{{ pvwa_artifact_name }}"
  register: st

- fail:
    msg: "{{ pvwa_zip_file_path }} not exists, failing..."
  when: not st.stat.exists

- name: check if package is valid using checksum
  fail:
    msg: "Checksum does not match, please validate your package."
  when:
    - st.stat.checksum !=  pvwa_sha1_checksum
    - not pvwa_ignore_checksum

- name: Unzip the pvwa package
  win_unzip:
    src: "{{ pvwa_extract_folder }}\\{{ pvwa_artifact_name }}"
    dest: "{{ pvwa_extract_folder }}"

- name: Copy registration tool
  win_copy:
    src: "{{ pvwa_installationautomation_folder }}\\Registration\\RegistrationTool\\"
    dest: "{{ pvwa_registrationtool_folder }}"
    remote_src: yes
